### ISSUE TITLE
Promise Handler eating errors

### ISSUE THREAD

**Issue by warbrett** [iceddev/cooldux#1]
More of a discussion than a bug but:
https://github.com/iceddev/cooldux/blob/master/index.js#L46

Here promiseHandler ends up gobbling up errors. Which means if I have a create method using it inside of a react component like so:

```
createMethod(someData)
  .then((success) => {
     this.setState({
       msg: 'thing successfully created'
     })
   })
```

It will always say thing was created. I'd prefer to explicitly handle the error myself by rethrowing it rather than just returning null, however I can see why some people might prefer the existing implementation.

How do you feel about throwing here vs returning the null?

**Comment by monteslu** [comment]
@warbrett it puts the error on a somethingError property in the state.  The idea was that any throws are dealt with in the view by checking for one of those error properties or doing something with that error in your reducer.

**Comment by monteslu** [comment]
One thing that might not be clear though is that its leaving the result in state, where it might make more sense to null out any existing result property (in my example just `something`) on a failure instead of just adding the Error

**Comment by warbrett** [comment]
A successful and a failed query both return a null in my case. So I can't differentiate between them in the next then to handle local state updates. And if there isn't an error no props change so it's not a case I can handle it within componentWillReceiveProps. It kind of makes promisehandler useless for that case

**Comment by monteslu** [comment]
ahh ok, I forgot it was even returning the promise at all.  
the return here https://github.com/iceddev/cooldux/blob/master/index.js#L40 wasn't intentional

But since it is there...

If we throw in that catch won't we get warnings about not handling it if we don't want to catch it ourselves?

**Comment by warbrett** [comment]
Yeah thats kind of the problem, the way it handles it now is a weird state of technically correct but kind of problematic. I think the current implementation is right for the majority of use cases though. What if it took an optional options object with throwError: true ?

**Comment by monteslu** [comment]
v 0.5.0 published
